apiVersion: v1
kind: Service
metadata:
  name: wedding-service
spec:
  selector:
    app: wedding
  ports:
    - protocol: TCP
      port: 80          # 서비스가 노출할 포트 (Ingress에서 접근)
      targetPort: 3000  # 파드가 실제로 사용하는 포트
  type: ClusterIP
