name: wedding to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v3

    - name: Docker 로그인
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Docker 이미지 빌드
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/wedding:latest -t ${{ secrets.DOCKER_USERNAME }}/wedding:${{ github.sha }} .

    - name: Docker 이미지 푸시
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/wedding:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/wedding:${{ github.sha }}

    - name: kubeconfig 설정
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

    - name: Kubernetes Secret 생성/업데이트
      run: |
        kubectl create secret generic wedding-secret \
          --from-literal=NOTION_TOKEN=${{ secrets.NOTION_TOKEN }} \
          --from-literal=DATABASE_ID=${{ secrets.DATABASE_ID }} \
          --namespace=wedding \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Kubernetes 배포 (이미지 롤링 업데이트)
      run: |
        kubectl set image deployment/wedding-deployment wedding-container=${{ secrets.DOCKER_USERNAME }}/wedding:latest --namespace=wedding

    - name: Test API server connectivity
      run: |
        curl -vk https://kschost.ddns.net:6443 || true
